name: Download APK from APKMirror

on:
  workflow_dispatch:

jobs:
  download-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y pup jq tree

      - name: Scrape APKMirror for latest YouTube APK
        run: |
          APKMIRROR_URL="https://www.apkmirror.com/apk/google-inc/youtube"
          PAGE_URL=$(curl -s $APKMIRROR_URL | pup 'div.appRow a attr{href}' | grep 'download' | head -n 1)
          FULL_PAGE_URL="https://www.apkmirror.com$PAGE_URL"
          echo "Found page: $FULL_PAGE_URL"

          DOWNLOAD_PAGE=$(curl -s "$FULL_PAGE_URL" | pup 'a.button.downloadButton attr{href}' | head -n 1)
          FINAL_URL="https://www.apkmirror.com$DOWNLOAD_PAGE"

          echo "Downloading from: $FINAL_URL"
          curl -L "$FINAL_URL" -o YouTube.apk

      - name: Log files
        run: |
          ls -lah
          tree ./

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTube-apk
          path: YouTube.apk
